### PR TITLE
issue-534: fix panic in cases when --failfast flag is set

### LINKED ISSUE #534: panic: runtime error: invalid memory address or nil pointer dereference with `--failfast`
**Describe the bug**
I have a [big helm chart that's using unittest](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/tests) and it's crashing with this message:

```text
helm unittest --failfast --with-subchart=false .

### Chart [ k8s-monitoring ] .

 PASS  Test Beyla config values tests/beyla_config_test.yaml
 FAIL  Cluster Events feature tests     tests/cluster_events_test.yaml
        - requires a log destination
                Error: execution error at (k8s-monitoring/templates/validations.yaml:10:6): 
No destinations found that can accept logs from Kubernetes Cluster events
Please add a destination with logs support.
See https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/destinations/README.md for more details.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ea5960]

goroutine 1 [running]:
github.com/helm-unittest/helm-unittest/pkg/unittest/results.TestSuiteResult.Print({{0x1400082d940, 0x1c}, {0x140002ce436, 0x1e}, 0x0, {0x0, 0x0}, {0x14000753d40, 0x7, 0x7}, ...}, ...)
        /home/runner/work/helm-unittest/helm-unittest/pkg/unittest/results/test_suite_result.go:57 +0x150
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).handleSuiteResult(0x102d2e920, 0x140002aa620)
        /home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:237 +0x94
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).runV3SuitesOfChart(0x102d2e920, {0x140006808a0, 0x6, 0x16f2cb41d?}, {0x16f2cb41d, 0x1})
        /home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:215 +0x1bc
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).RunV3(0x102d2e920, {0x140003403c0, 0x1, 0x0?})
        /home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:106 +0x138
main.RunPlugin(0x140000f8700?, {0x140003403c0, 0x1, 0x3})
        /home/runner/work/helm-unittest/helm-unittest/cmd/helm-unittest/helm_unittest.go:112 +0x2d8
github.com/spf13/cobra.(*Command).execute(0x102d17d60, {0x140001b2090, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x102d17d60)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        /home/runner/work/helm-unittest/helm-unittest/cmd/helm-unittest/helm_unittest.go:121 +0x24
Error: plugin "unittest" exited with error
make: *** [unittest] Error 2
```

The stack trace points to the `result.print` here:
https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/results/test_suite_result.go#L57

It works when I remove `--failfast`, so I wonder if a nil test result is being added to the slice when it hasn't executed yet.

**To Reproduce**
1. Example helm project
2. Example test scenario

**Expected behavior**
It should work with or without `--failfast`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Plugin Version 0.7.1

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
resolves #534 

Under certain conditiions the `--failfast` flag was applied to a suite, but following suites where still executing. As per description the suits/tests should be skipped without any null pointers. This is fixed.

Notes:
- results/test_suite_result.go added null check and improved test coverage 
- added multiple tests on different layers
- added null checks where required
- tested with grafana chart https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/tests
- tested with some private charts as well

current behaviour
Screenshot 2025-01-10 at 19 19 01

with the fix
Screenshot 2025-01-10 at 20 55 17

### CODE REVIEW

File: pkg/unittest/test_suite.go [hunk 1]
```diff
@@ -328,35 +332,44 @@ func (s *TestSuite) polishChartSettings(test *TestJob) {
...
 	jobResults := make([]*results.TestJobResult, len(s.Tests))
 
-	for idx, testJob := range s.Tests {
-		// (Re)load the chart used by this suite (with logging temporarily disabled)
-		log.SetOutput(io.Discard)
-		chart, _ := v3loader.Load(chartPath)
-		log.SetOutput(os.Stdout)
+	// (Re)load the chart used by this suite (with logging temporarily disabled)
+	log.SetOutput(io.Discard)
+	// TODO: is this required? As we are loading the chart in the test runner RunV3
```
Comment (quintush) [inline pkg/unittest/test_suite.go:352]: Reloading the chart is required to ensure the default values are reset back. Otherwise we risk values overridden by previous tests are reused.

**Review by quintush — COMMENTED** [review]
Based on the changes it seems the failfast was only applicable to a single suite.

Good catch and thanks for the quick fix!

Greetings 
@quintush

File: pkg/unittest/test_suite.go (hunk 1 above)
Comment (ivankatliarchuk) [reply pkg/unittest/test_suite.go:352]: Gotcha. Moved back. Strange, that no tests are failing. Worth to consider in follow-up most likely to improve this line. As If there enormous number of tests, it could be reloaded quite a few times.

**Comment by ivankatliarchuk** [comment]
Yep. Thand for early review @quintush . This fix looks like ready for review/merge

File: pkg/unittest/test_suite.go [hunk 2]
```diff
@@ -328,35 +332,44 @@ func (s *TestSuite) polishChartSettings(test *TestJob) {
...
 func (s *TestSuite) runV3TestJobs(
 	chartPath string,
 	cache *snapshot.Cache,
-	failfast bool,
+	failFast bool,
 	renderPath string,
-) (bool, []*results.TestJobResult) {
-	suitePass := false
+) *SuiteResult {
+	result := SuiteResult{Pass: true, FailFast: false}
```
Comment (quintush) [inline pkg/unittest/test_suite.go:347]: I would prefer to have the default value of Pass to be false, so that the testresults are failing when something unexpected happens.

**Review by quintush — CHANGES_REQUESTED** [review]

File: pkg/unittest/test_suite.go (hunk 2 above)
Comment (ivankatliarchuk) [reply pkg/unittest/test_suite.go]: Make sense. Changed

**Review by quintush — APPROVED** [review]
